name: example
description: A starting point for Dart libraries or applications.
version: 0.1.6
#homepage: https://www.example.com
#author: alois <email@example.com>

environment:
  sdk: '>2.0.0-dev <3.0.0'

dependencies:
  dioc: ^0.1.6 

dev_dependencies:
  test: 
  build_runner:
  dioc_generator:
    path: ../
  pedantic: ^1.8.0+1
