name: dioc_generator
description: A generator of code for dioc containers.
version: 0.1.2
homepage: https://github.com/aloisdeniel/dioc
author: Aloïs Deniel <alois.deniel@outlook.com>

environment:
  sdk: '>2.0.0-dev <3.0.0'

dependencies:
  analyzer: ^0.32.4
  build: ^0.12.7+3
  dart_style: ^1.1.3
  source_gen: ^0.9.0+1
  code_builder: ^3.1.3
  build_test: ^0.10.3+1
  build_runner: ^0.10.1+1
  dioc: ^0.1.2
    #path: ../dioc

dev_dependencies:
  test:
