name: dioc_generator
description: A generator of code for dioc containers.
version: 0.1.6
homepage: https://github.com/aloisdeniel/dioc
author: Aloïs Deniel <alois.deniel@outlook.com>

environment:
  sdk: '>2.0.0-dev <3.0.0'

dependencies:
  analyzer: ^0.37.0
  build: ^1.1.5
  dart_style: ^1.2.9
  source_gen: ^0.9.4+3
  code_builder: ^3.2.0
  build_test: ^0.10.8
  build_runner: ^1.6.5
  dioc: ^0.1.6 
dev_dependencies:
  test:
  pedantic: ^1.8.0+1
